movieproject/movieproject/movieapp/urls.py
from django.urls import path
from . import views
app_name='movieapp'

urlpatterns = [
     path('',views.index,name='index'),
     path('movie/<int:movie_id>/',views.detail,name='detail'),
     path('add/',views.add_movie,name='add_movie'),
     path('update/<int:id>/',views.update,name='update'),
     path('delete/<int:id>/',views.delete,name='delete')
]

movieproject/movieproject/movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movieproject/movieproject/movieapp/models.py
from django.db import models

class movie(models.Model):
    name=models.CharField(max_length=250)
    description=models.TextField()
    year=models.IntegerField()
    image=models.ImageField(upload_to='gallery')

    def __str__(self):
       return self.name

movieproject/movieproject/movieapp/forms.py
from django import forms
from . models import movie

class movieform(forms.ModelForm):
    class Meta:
       model=movie
       fields=['name','description','year','image']

movieproject/movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from .models import movie
from . forms import movieform


def index(request):
   mov=movie.objects.all()
   context={
              'movie_list':mov
    }
   return render(request,'index.html',context)

def detail(request,movie_id):
    mov=movie.objects.get(id=movie_id)
    return render(request,"detail.html",{'movie':mov})
def add_movie(request):
    if request.method=="POST":
        name=request.POST.get('name',)
        description=request.POST.get('description',)
        year=request.POST.get('year',)
        image=request.FILES['image']
        mov=movie(name=name,description=description,year=year,image=image)
        mov.save()
    return render(request,"add.html")

def update(request,id):
    mov=movie.objects.get(id=id)
    form=movieform(request.POST or None,request.FILES,instance=mov)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,"edit.html",{'form':form ,'movie':mov})

def delete(request,id):
    if request.method=='POST':
        mov=movie.objects.get(id=id)
        mov.delete()
        return redirect('/')
    return render(request,"delete.html")

movieproject/movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="text" name="name" placeholder="enter your movie name">
  <input type="text" name="description" placeholder="enter your movie description">
  <input type="text" name="year" placeholder="enter movie year">
  <input type="file" name="image">
  <input type="submit">


</form>
 {% endblock %}

movieproject/movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"></head>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
      online movie store
  </a>
</nav>
{% block body %}
{% endblock %}

</body>
</html>

movieproject/movieproject/templates/delete.html
<form method="POST">
    {% csrf_token %}
    are you wanted to delete this movie?
    <input type="submit">
</form>

movieproject/movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.image.url}}"width="300" height="300";>
        </div>
        <div class="col-md-6">
           <h2>{{movie.name}}</h2>
          <h4>{{movie.description}}</h4>
            <h4>{{movie.year}}</h4>
            <a class="btn btn-warning" href="{%url 'movieapp:update' movie.id %}">update</a>
            <a class="btn btn-danger" href="{%url 'movieapp:delete' movie.id %}">delete</a>

        </div>

    </div>
</div>
{% endblock %}

movieproject/movieproject/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
 <input type="submit">
</form>

movieproject/movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        {% for i in movie_list %}
        <div class="col-md-3">
            <div class="card" style="margin-right:20px;margin-top:20px;">
 <img class="card-img-top" src="{{i.image.url}}" alt="Card image cap" height="250px;">
  <div class="card-body">
    <h5 class="card_title">{{i.name}}</h5>
    <p class="card-text">{{i.description}}</p>
    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">Go somewhere</a>
  </div>
</div>

        </div>
        {% endfor %}

    </div>

</div>
{% endblock %}